clean:
	@rm -rf csrc simv.daidir simv ucli.key vc_hdrs.h
run:
	vcs -full64 -sverilog test.v -ntb_opts uvm-1.2 -R -q
run1:
	vcs -full64 -sverilog test1.v -ntb_opts uvm-1.2 -R -q
run2:
	vcs -full64 -sverilog test2.v -ntb_opts uvm-1.2 -R -q
run3:
	vcs -full64 -sverilog test3.v -ntb_opts uvm-1.2 -R -q
run4:
	vcs -full64 -sverilog test4.v -ntb_opts uvm-1.2 -R -q
run5:
	vcs -full64 -sverilog test5.v -ntb_opts uvm-1.2 -R -q
run6:
	vcs -full64 -sverilog test6.v -ntb_opts uvm-1.2 -R -q
run7:
	vcs -full64 -sverilog test7.v -ntb_opts uvm-1.2 -R -q
run8:
	vcs -full64 -sverilog test8.v -ntb_opts uvm-1.2 -R -q
