clean:
	@rm -rf csrc simv.daidir simv ucli.key vc_hdrs.h
run:
	vcs -full64 -sverilog test.v -ntb_opts uvm-1.2 -R -q
run1:
	vcs -full64 -sverilog test1.v -ntb_opts uvm-1.2 -R -q
run2:
	vcs -full64 -sverilog test2.v -ntb_opts uvm-1.2 -R -q
